---
# defaults file for grav
grav_url: http://getgrav.org/download/core/grav/latest
grav_dest: /var/www
grav_change_user_dir_group_permissions: no
grav_webserver_port: 80
grav_webserver_user: www-data
# use_supervisord: yes
